### ISSUE TITLE
Get all tests passing with DB2

### ISSUE THREAD

**Issue by aguibert** [hibernate/hibernate-reactive#162]

**Comment by gavinking** [comment]
It seems to me that this can be closed now.

**Comment by DavideD** [comment]
I think @aguibert is still working on this

**Comment by gavinking** [comment]
Seems to work AFAICT.

**Comment by gavinking** [comment]
@aguibert is there any reason we need to keep this open?

**Comment by aguibert** [comment]
I'm still working on it -- I have some tests disabled on DB2 that were failing initially and require more investigation. (Comments that contain `TODO @AGG` if you're curious)

**Comment by gavinking** [comment]
Well in `ReactiveSessionTest` it's `reactiveQueryWithLock()` that's the problem.

And in `BasicTypesAndCallbacksTest` it's because of the binary types and suchlike.

So AFAIK these just reflect limitations of the SB2 `SqlClient`, right?

**Comment by gavinking** [comment]
Oh well, I'm wrong. I didn't realize that the test suite produces hundreds of these traces:

```
[2020-05-26 17:00:25] SEVERE io.vertx.db2client.impl.codec.DB2Decoder                FATAL: Error parsing buffer at index 49 / 0x31
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 26 d0 52 00 01 00 20 22 18 00 06 11 49 00 00 |.&.R... "....I..|
|00000010| 00 16 21 10 c8 d9 c5 c1 c3 e3 40 40 40 40 40 40 |..!.......@@@@@@|
|00000020| 40 40 40 40 40 40 00 0b d0 43 00 01 00 05 24 08 |@@@@@@...C....$.|
|00000030| ff 00 2b d0 52 00 02 00 25 22 0c 00 06 11 49 00 |..+.R...%"....I.|
|00000040| 04 00 05 21 15 01 00 16 21 10 c8 d9 c5 c1 c3 e3 |...!....!.......|
|00000050| 40 40 40 40 40 40 40 40 40 40 40 40 00 0b d0 03 |@@@@@@@@@@@@....|
|00000060| 00 02 00 05 24 08 ff                            |....$..         |
+--------+-------------------------------------------------+----------------+
java.lang.NullPointerException
	at io.vertx.db2client.impl.drda.DRDAQueryResponse.parseEXCSQLSTTreply(DRDAQueryResponse.java:551)
	at io.vertx.db2client.impl.drda.DRDAQueryResponse.readExecute(DRDAQueryResponse.java:238)
	at io.vertx.db2client.impl.codec.ExtendedQueryCommandBaseCodec.handleUpdateResult(ExtendedQueryCommandBaseCodec.java:93)
	at io.vertx.db2client.impl.codec.ExtendedQueryCommandCodec.decodeUpdate(ExtendedQueryCommandCodec.java:57)
	at io.vertx.db2client.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:71)
	at io.vertx.db2client.impl.codec.DB2Decoder.decodePayload(DB2Decoder.java:80)
	at io.vertx.db2client.impl.codec.DB2Decoder.decode(DB2Decoder.java:53)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

Gradle doesn't display them to me so I had not noticed before.

(But I just ran the test in the IDE.)

**Comment by gavinking** [comment]
But that *must* be a bug in the DB2 `SqlClient`.

**Comment by aguibert** [comment]
Yep, the NPE is a bug in the DB2 driver that Davide pointed out shortly after we introduced DB2. I've fixed it over in Vertx so we'll scoop that up on the next Vertx release

**Comment by gavinking** [comment]
Ah, OK, 👍

**Comment by aguibert** [comment]
I am planning to do the remaining investigation later today and hopefully close this one out by EOD. Yesterday was a US holiday so I'm just returning today

**Comment by aguibert** [comment]
At the moment I've enabled as many tests as possible on DB2 given Vertx 3.9.1. I have some fixes that will go into 3.9.2 which will allow us to enable a few more tests too.

@gavinking I haven't been able to properly track down the lock-related test issues in `ReactiveSessionTest`. Do you expect this is because of DB2s server-side locking behavior? It doesn't seem like the DB2 client is behind these failures since the locking information is flowed as part of the SQL statement to the DB.

**Comment by gavinking** [comment]
> Do you expect this is because of DB2s server-side locking behavior? 

Honestly I have no clue. And I wasn't really very motivated to investigate it further while I'm still getting those logged error traces...

**Comment by gavinking** [comment]
I'm closing this out-of-date issue, since almost all tests now run perfectly on DB2, except for those related to BLOB/CLOB/BINARY.
